---
server:
    install: '1'
    timezone: Europe/Paris
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: localhost, ip: 10.0.0.10, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: pep-project.dev
pgsql:
    install: '1'
    database: symfony
    user: root
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-fpm, php5-mysql, php5-pgsql]

